default: &default
  expected_size: 500_000
  error_rate: 0.05
  provider: rebloom

development:
  <<: *default

test:
  storage:
    expected_size: 500_000
    error_rate: 0.05
    provider: memory

production:
  <<: *default
