base: &base
  expected_size: 500_000
  error_rate: 0.05
  provider: rebloom

development:
  <<: *base

test:
  <<: *base
  expected_size: 500_000
  error_rate: 0.05
  provider: memory

production:
  <<: *base
