default: &default
  expected_size: 500_000
  error_rate: 0.05
  provider: memory
  provider_config:
    url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

development:
  <<: *default

test:
  storage:
    expected_size: 500_000
    error_rate: 0.05
    provider: memory

production:
  <<: *default
