default: &default
  allowed_hosts:
    - stanko.io
    - blog.stanko.io
    - stanko.test
    - blog.stanko.test
    - 127.0.0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
