default: &default
  default_host: 'http://stanko.test'
  allowed_hosts:
    - stanko.io
    - stanko.test
    - 127.0.0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  default_host: 'https://stanko.io'
